### GET all users
GET http://localhost:8080/backend_news_war_exploded/users

### GET user by id
GET http://localhost:8080/backend_news_war_exploded/users/1

### Register user
POST /backend_news_war_exploded/registration HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Danik",
  "password": "123123gG",
  "email": "danik@example.com"
}

### Update user
PUT /backend_news_war_exploded/users/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "password": "8521581",
  "email": "john.filroch@example.com"
}

### Login
POST /backend_news_war_exploded/login
Host: localhost:8080
Content-Type: application/json

{
  "username": "John",
  "password": "123456"
}
